package com.hycon.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tx.proto

public final class TxOuterClass {
  private TxOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TxsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Txs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    java.util.List<TxOuterClass.Tx> 
        getTxsList();
    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    TxOuterClass.Tx getTxs(int index);
    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    int getTxsCount();
    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    java.util.List<? extends TxOuterClass.TxOrBuilder> 
        getTxsOrBuilderList();
    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    TxOuterClass.TxOrBuilder getTxsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Txs}
   */
  public  static final class Txs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Txs)
      TxsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Txs.newBuilder() to construct.
    private Txs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Txs() {
      txs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Txs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                txs_ = new java.util.ArrayList<TxOuterClass.Tx>();
                mutable_bitField0_ |= 0x00000001;
              }
              txs_.add(
                  input.readMessage(TxOuterClass.Tx.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          txs_ = java.util.Collections.unmodifiableList(txs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TxOuterClass.internal_static_Txs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TxOuterClass.internal_static_Txs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TxOuterClass.Txs.class, TxOuterClass.Txs.Builder.class);
    }

    public static final int TXS_FIELD_NUMBER = 1;
    private java.util.List<TxOuterClass.Tx> txs_;
    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    public java.util.List<TxOuterClass.Tx> getTxsList() {
      return txs_;
    }
    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    public java.util.List<? extends TxOuterClass.TxOrBuilder> 
        getTxsOrBuilderList() {
      return txs_;
    }
    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    public int getTxsCount() {
      return txs_.size();
    }
    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    public TxOuterClass.Tx getTxs(int index) {
      return txs_.get(index);
    }
    /**
     * <code>repeated .Tx txs = 1;</code>
     */
    public TxOuterClass.TxOrBuilder getTxsOrBuilder(
        int index) {
      return txs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < txs_.size(); i++) {
        output.writeMessage(1, txs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < txs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, txs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TxOuterClass.Txs)) {
        return super.equals(obj);
      }
      TxOuterClass.Txs other = (TxOuterClass.Txs) obj;

      boolean result = true;
      result = result && getTxsList()
          .equals(other.getTxsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTxsCount() > 0) {
        hash = (37 * hash) + TXS_FIELD_NUMBER;
        hash = (53 * hash) + getTxsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TxOuterClass.Txs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxOuterClass.Txs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxOuterClass.Txs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxOuterClass.Txs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxOuterClass.Txs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxOuterClass.Txs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxOuterClass.Txs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxOuterClass.Txs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxOuterClass.Txs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TxOuterClass.Txs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxOuterClass.Txs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxOuterClass.Txs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TxOuterClass.Txs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Txs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Txs)
        TxOuterClass.TxsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TxOuterClass.internal_static_Txs_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TxOuterClass.internal_static_Txs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TxOuterClass.Txs.class, TxOuterClass.Txs.Builder.class);
      }

      // Construct using TxOuterClass.Txs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTxsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (txsBuilder_ == null) {
          txs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          txsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TxOuterClass.internal_static_Txs_descriptor;
      }

      public TxOuterClass.Txs getDefaultInstanceForType() {
        return TxOuterClass.Txs.getDefaultInstance();
      }

      public TxOuterClass.Txs build() {
        TxOuterClass.Txs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TxOuterClass.Txs buildPartial() {
        TxOuterClass.Txs result = new TxOuterClass.Txs(this);
        int from_bitField0_ = bitField0_;
        if (txsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            txs_ = java.util.Collections.unmodifiableList(txs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.txs_ = txs_;
        } else {
          result.txs_ = txsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TxOuterClass.Txs) {
          return mergeFrom((TxOuterClass.Txs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TxOuterClass.Txs other) {
        if (other == TxOuterClass.Txs.getDefaultInstance()) return this;
        if (txsBuilder_ == null) {
          if (!other.txs_.isEmpty()) {
            if (txs_.isEmpty()) {
              txs_ = other.txs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTxsIsMutable();
              txs_.addAll(other.txs_);
            }
            onChanged();
          }
        } else {
          if (!other.txs_.isEmpty()) {
            if (txsBuilder_.isEmpty()) {
              txsBuilder_.dispose();
              txsBuilder_ = null;
              txs_ = other.txs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              txsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTxsFieldBuilder() : null;
            } else {
              txsBuilder_.addAllMessages(other.txs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TxOuterClass.Txs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TxOuterClass.Txs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<TxOuterClass.Tx> txs_ =
        java.util.Collections.emptyList();
      private void ensureTxsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          txs_ = new java.util.ArrayList<TxOuterClass.Tx>(txs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          TxOuterClass.Tx, TxOuterClass.Tx.Builder, TxOuterClass.TxOrBuilder> txsBuilder_;

      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public java.util.List<TxOuterClass.Tx> getTxsList() {
        if (txsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(txs_);
        } else {
          return txsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public int getTxsCount() {
        if (txsBuilder_ == null) {
          return txs_.size();
        } else {
          return txsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public TxOuterClass.Tx getTxs(int index) {
        if (txsBuilder_ == null) {
          return txs_.get(index);
        } else {
          return txsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public Builder setTxs(
          int index, TxOuterClass.Tx value) {
        if (txsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxsIsMutable();
          txs_.set(index, value);
          onChanged();
        } else {
          txsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public Builder setTxs(
          int index, TxOuterClass.Tx.Builder builderForValue) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.set(index, builderForValue.build());
          onChanged();
        } else {
          txsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public Builder addTxs(TxOuterClass.Tx value) {
        if (txsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxsIsMutable();
          txs_.add(value);
          onChanged();
        } else {
          txsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public Builder addTxs(
          int index, TxOuterClass.Tx value) {
        if (txsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxsIsMutable();
          txs_.add(index, value);
          onChanged();
        } else {
          txsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public Builder addTxs(
          TxOuterClass.Tx.Builder builderForValue) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.add(builderForValue.build());
          onChanged();
        } else {
          txsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public Builder addTxs(
          int index, TxOuterClass.Tx.Builder builderForValue) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.add(index, builderForValue.build());
          onChanged();
        } else {
          txsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public Builder addAllTxs(
          java.lang.Iterable<? extends TxOuterClass.Tx> values) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, txs_);
          onChanged();
        } else {
          txsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public Builder clearTxs() {
        if (txsBuilder_ == null) {
          txs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          txsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public Builder removeTxs(int index) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.remove(index);
          onChanged();
        } else {
          txsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public TxOuterClass.Tx.Builder getTxsBuilder(
          int index) {
        return getTxsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public TxOuterClass.TxOrBuilder getTxsOrBuilder(
          int index) {
        if (txsBuilder_ == null) {
          return txs_.get(index);  } else {
          return txsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public java.util.List<? extends TxOuterClass.TxOrBuilder> 
           getTxsOrBuilderList() {
        if (txsBuilder_ != null) {
          return txsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(txs_);
        }
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public TxOuterClass.Tx.Builder addTxsBuilder() {
        return getTxsFieldBuilder().addBuilder(
            TxOuterClass.Tx.getDefaultInstance());
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public TxOuterClass.Tx.Builder addTxsBuilder(
          int index) {
        return getTxsFieldBuilder().addBuilder(
            index, TxOuterClass.Tx.getDefaultInstance());
      }
      /**
       * <code>repeated .Tx txs = 1;</code>
       */
      public java.util.List<TxOuterClass.Tx.Builder> 
           getTxsBuilderList() {
        return getTxsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          TxOuterClass.Tx, TxOuterClass.Tx.Builder, TxOuterClass.TxOrBuilder> 
          getTxsFieldBuilder() {
        if (txsBuilder_ == null) {
          txsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              TxOuterClass.Tx, TxOuterClass.Tx.Builder, TxOuterClass.TxOrBuilder>(
                  txs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          txs_ = null;
        }
        return txsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Txs)
    }

    // @@protoc_insertion_point(class_scope:Txs)
    private static final TxOuterClass.Txs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TxOuterClass.Txs();
    }

    public static TxOuterClass.Txs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Txs>
        PARSER = new com.google.protobuf.AbstractParser<Txs>() {
      public Txs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Txs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Txs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Txs> getParserForType() {
      return PARSER;
    }

    public TxOuterClass.Txs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Tx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Consensus Critical
     * </pre>
     *
     * <code>bytes from = 1;</code>
     */
    com.google.protobuf.ByteString getFrom();

    /**
     * <pre>
     *Address
     * </pre>
     *
     * <code>bytes to = 2;</code>
     */
    com.google.protobuf.ByteString getTo();

    /**
     * <code>uint64 amount = 3;</code>
     */
    long getAmount();

    /**
     * <code>uint64 fee = 4;</code>
     */
    long getFee();

    /**
     * <code>uint32 nonce = 5;</code>
     */
    int getNonce();

    /**
     * <code>bytes signature = 6;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>uint32 recovery = 7;</code>
     */
    int getRecovery();

    /**
     * <code>bytes transitionSignature = 8;</code>
     */
    com.google.protobuf.ByteString getTransitionSignature();

    /**
     * <code>uint32 transitionRecovery = 9;</code>
     */
    int getTransitionRecovery();

    /**
     * <code>string networkid = 10;</code>
     */
    java.lang.String getNetworkid();
    /**
     * <code>string networkid = 10;</code>
     */
    com.google.protobuf.ByteString
        getNetworkidBytes();
  }
  /**
   * Protobuf type {@code Tx}
   */
  public  static final class Tx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Tx)
      TxOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tx.newBuilder() to construct.
    private Tx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tx() {
      from_ = com.google.protobuf.ByteString.EMPTY;
      to_ = com.google.protobuf.ByteString.EMPTY;
      amount_ = 0L;
      fee_ = 0L;
      nonce_ = 0;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      recovery_ = 0;
      transitionSignature_ = com.google.protobuf.ByteString.EMPTY;
      transitionRecovery_ = 0;
      networkid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              from_ = input.readBytes();
              break;
            }
            case 18: {

              to_ = input.readBytes();
              break;
            }
            case 24: {

              amount_ = input.readUInt64();
              break;
            }
            case 32: {

              fee_ = input.readUInt64();
              break;
            }
            case 40: {

              nonce_ = input.readUInt32();
              break;
            }
            case 50: {

              signature_ = input.readBytes();
              break;
            }
            case 56: {

              recovery_ = input.readUInt32();
              break;
            }
            case 66: {

              transitionSignature_ = input.readBytes();
              break;
            }
            case 72: {

              transitionRecovery_ = input.readUInt32();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              networkid_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TxOuterClass.internal_static_Tx_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TxOuterClass.internal_static_Tx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TxOuterClass.Tx.class, TxOuterClass.Tx.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString from_;
    /**
     * <pre>
     * Consensus Critical
     * </pre>
     *
     * <code>bytes from = 1;</code>
     */
    public com.google.protobuf.ByteString getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString to_;
    /**
     * <pre>
     *Address
     * </pre>
     *
     * <code>bytes to = 2;</code>
     */
    public com.google.protobuf.ByteString getTo() {
      return to_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private long amount_;
    /**
     * <code>uint64 amount = 3;</code>
     */
    public long getAmount() {
      return amount_;
    }

    public static final int FEE_FIELD_NUMBER = 4;
    private long fee_;
    /**
     * <code>uint64 fee = 4;</code>
     */
    public long getFee() {
      return fee_;
    }

    public static final int NONCE_FIELD_NUMBER = 5;
    private int nonce_;
    /**
     * <code>uint32 nonce = 5;</code>
     */
    public int getNonce() {
      return nonce_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 6;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int RECOVERY_FIELD_NUMBER = 7;
    private int recovery_;
    /**
     * <code>uint32 recovery = 7;</code>
     */
    public int getRecovery() {
      return recovery_;
    }

    public static final int TRANSITIONSIGNATURE_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString transitionSignature_;
    /**
     * <code>bytes transitionSignature = 8;</code>
     */
    public com.google.protobuf.ByteString getTransitionSignature() {
      return transitionSignature_;
    }

    public static final int TRANSITIONRECOVERY_FIELD_NUMBER = 9;
    private int transitionRecovery_;
    /**
     * <code>uint32 transitionRecovery = 9;</code>
     */
    public int getTransitionRecovery() {
      return transitionRecovery_;
    }

    public static final int NETWORKID_FIELD_NUMBER = 10;
    private volatile java.lang.Object networkid_;
    /**
     * <code>string networkid = 10;</code>
     */
    public java.lang.String getNetworkid() {
      java.lang.Object ref = networkid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        networkid_ = s;
        return s;
      }
    }
    /**
     * <code>string networkid = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNetworkidBytes() {
      java.lang.Object ref = networkid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        networkid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!from_.isEmpty()) {
        output.writeBytes(1, from_);
      }
      if (!to_.isEmpty()) {
        output.writeBytes(2, to_);
      }
      if (amount_ != 0L) {
        output.writeUInt64(3, amount_);
      }
      if (fee_ != 0L) {
        output.writeUInt64(4, fee_);
      }
      if (nonce_ != 0) {
        output.writeUInt32(5, nonce_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(6, signature_);
      }
      if (recovery_ != 0) {
        output.writeUInt32(7, recovery_);
      }
      if (!transitionSignature_.isEmpty()) {
        output.writeBytes(8, transitionSignature_);
      }
      if (transitionRecovery_ != 0) {
        output.writeUInt32(9, transitionRecovery_);
      }
      if (!getNetworkidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, networkid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!from_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, from_);
      }
      if (!to_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, to_);
      }
      if (amount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, amount_);
      }
      if (fee_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, fee_);
      }
      if (nonce_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, nonce_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, signature_);
      }
      if (recovery_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, recovery_);
      }
      if (!transitionSignature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, transitionSignature_);
      }
      if (transitionRecovery_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, transitionRecovery_);
      }
      if (!getNetworkidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, networkid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TxOuterClass.Tx)) {
        return super.equals(obj);
      }
      TxOuterClass.Tx other = (TxOuterClass.Tx) obj;

      boolean result = true;
      result = result && getFrom()
          .equals(other.getFrom());
      result = result && getTo()
          .equals(other.getTo());
      result = result && (getAmount()
          == other.getAmount());
      result = result && (getFee()
          == other.getFee());
      result = result && (getNonce()
          == other.getNonce());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && (getRecovery()
          == other.getRecovery());
      result = result && getTransitionSignature()
          .equals(other.getTransitionSignature());
      result = result && (getTransitionRecovery()
          == other.getTransitionRecovery());
      result = result && getNetworkid()
          .equals(other.getNetworkid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAmount());
      hash = (37 * hash) + FEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFee());
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + RECOVERY_FIELD_NUMBER;
      hash = (53 * hash) + getRecovery();
      hash = (37 * hash) + TRANSITIONSIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getTransitionSignature().hashCode();
      hash = (37 * hash) + TRANSITIONRECOVERY_FIELD_NUMBER;
      hash = (53 * hash) + getTransitionRecovery();
      hash = (37 * hash) + NETWORKID_FIELD_NUMBER;
      hash = (53 * hash) + getNetworkid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TxOuterClass.Tx parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxOuterClass.Tx parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxOuterClass.Tx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxOuterClass.Tx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxOuterClass.Tx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxOuterClass.Tx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxOuterClass.Tx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxOuterClass.Tx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxOuterClass.Tx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TxOuterClass.Tx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxOuterClass.Tx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxOuterClass.Tx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TxOuterClass.Tx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Tx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Tx)
        TxOuterClass.TxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TxOuterClass.internal_static_Tx_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TxOuterClass.internal_static_Tx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TxOuterClass.Tx.class, TxOuterClass.Tx.Builder.class);
      }

      // Construct using TxOuterClass.Tx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = com.google.protobuf.ByteString.EMPTY;

        to_ = com.google.protobuf.ByteString.EMPTY;

        amount_ = 0L;

        fee_ = 0L;

        nonce_ = 0;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        recovery_ = 0;

        transitionSignature_ = com.google.protobuf.ByteString.EMPTY;

        transitionRecovery_ = 0;

        networkid_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TxOuterClass.internal_static_Tx_descriptor;
      }

      public TxOuterClass.Tx getDefaultInstanceForType() {
        return TxOuterClass.Tx.getDefaultInstance();
      }

      public TxOuterClass.Tx build() {
        TxOuterClass.Tx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TxOuterClass.Tx buildPartial() {
        TxOuterClass.Tx result = new TxOuterClass.Tx(this);
        result.from_ = from_;
        result.to_ = to_;
        result.amount_ = amount_;
        result.fee_ = fee_;
        result.nonce_ = nonce_;
        result.signature_ = signature_;
        result.recovery_ = recovery_;
        result.transitionSignature_ = transitionSignature_;
        result.transitionRecovery_ = transitionRecovery_;
        result.networkid_ = networkid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TxOuterClass.Tx) {
          return mergeFrom((TxOuterClass.Tx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TxOuterClass.Tx other) {
        if (other == TxOuterClass.Tx.getDefaultInstance()) return this;
        if (other.getFrom() != com.google.protobuf.ByteString.EMPTY) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != com.google.protobuf.ByteString.EMPTY) {
          setTo(other.getTo());
        }
        if (other.getAmount() != 0L) {
          setAmount(other.getAmount());
        }
        if (other.getFee() != 0L) {
          setFee(other.getFee());
        }
        if (other.getNonce() != 0) {
          setNonce(other.getNonce());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (other.getRecovery() != 0) {
          setRecovery(other.getRecovery());
        }
        if (other.getTransitionSignature() != com.google.protobuf.ByteString.EMPTY) {
          setTransitionSignature(other.getTransitionSignature());
        }
        if (other.getTransitionRecovery() != 0) {
          setTransitionRecovery(other.getTransitionRecovery());
        }
        if (!other.getNetworkid().isEmpty()) {
          networkid_ = other.networkid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TxOuterClass.Tx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TxOuterClass.Tx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString from_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Consensus Critical
       * </pre>
       *
       * <code>bytes from = 1;</code>
       */
      public com.google.protobuf.ByteString getFrom() {
        return from_;
      }
      /**
       * <pre>
       * Consensus Critical
       * </pre>
       *
       * <code>bytes from = 1;</code>
       */
      public Builder setFrom(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Consensus Critical
       * </pre>
       *
       * <code>bytes from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString to_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *Address
       * </pre>
       *
       * <code>bytes to = 2;</code>
       */
      public com.google.protobuf.ByteString getTo() {
        return to_;
      }
      /**
       * <pre>
       *Address
       * </pre>
       *
       * <code>bytes to = 2;</code>
       */
      public Builder setTo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Address
       * </pre>
       *
       * <code>bytes to = 2;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }

      private long amount_ ;
      /**
       * <code>uint64 amount = 3;</code>
       */
      public long getAmount() {
        return amount_;
      }
      /**
       * <code>uint64 amount = 3;</code>
       */
      public Builder setAmount(long value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 amount = 3;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0L;
        onChanged();
        return this;
      }

      private long fee_ ;
      /**
       * <code>uint64 fee = 4;</code>
       */
      public long getFee() {
        return fee_;
      }
      /**
       * <code>uint64 fee = 4;</code>
       */
      public Builder setFee(long value) {
        
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 fee = 4;</code>
       */
      public Builder clearFee() {
        
        fee_ = 0L;
        onChanged();
        return this;
      }

      private int nonce_ ;
      /**
       * <code>uint32 nonce = 5;</code>
       */
      public int getNonce() {
        return nonce_;
      }
      /**
       * <code>uint32 nonce = 5;</code>
       */
      public Builder setNonce(int value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 nonce = 5;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 6;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 6;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 6;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private int recovery_ ;
      /**
       * <code>uint32 recovery = 7;</code>
       */
      public int getRecovery() {
        return recovery_;
      }
      /**
       * <code>uint32 recovery = 7;</code>
       */
      public Builder setRecovery(int value) {
        
        recovery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 recovery = 7;</code>
       */
      public Builder clearRecovery() {
        
        recovery_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString transitionSignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes transitionSignature = 8;</code>
       */
      public com.google.protobuf.ByteString getTransitionSignature() {
        return transitionSignature_;
      }
      /**
       * <code>bytes transitionSignature = 8;</code>
       */
      public Builder setTransitionSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transitionSignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes transitionSignature = 8;</code>
       */
      public Builder clearTransitionSignature() {
        
        transitionSignature_ = getDefaultInstance().getTransitionSignature();
        onChanged();
        return this;
      }

      private int transitionRecovery_ ;
      /**
       * <code>uint32 transitionRecovery = 9;</code>
       */
      public int getTransitionRecovery() {
        return transitionRecovery_;
      }
      /**
       * <code>uint32 transitionRecovery = 9;</code>
       */
      public Builder setTransitionRecovery(int value) {
        
        transitionRecovery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 transitionRecovery = 9;</code>
       */
      public Builder clearTransitionRecovery() {
        
        transitionRecovery_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object networkid_ = "";
      /**
       * <code>string networkid = 10;</code>
       */
      public java.lang.String getNetworkid() {
        java.lang.Object ref = networkid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          networkid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string networkid = 10;</code>
       */
      public com.google.protobuf.ByteString
          getNetworkidBytes() {
        java.lang.Object ref = networkid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          networkid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string networkid = 10;</code>
       */
      public Builder setNetworkid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        networkid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string networkid = 10;</code>
       */
      public Builder clearNetworkid() {
        
        networkid_ = getDefaultInstance().getNetworkid();
        onChanged();
        return this;
      }
      /**
       * <code>string networkid = 10;</code>
       */
      public Builder setNetworkidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        networkid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Tx)
    }

    // @@protoc_insertion_point(class_scope:Tx)
    private static final TxOuterClass.Tx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TxOuterClass.Tx();
    }

    public static TxOuterClass.Tx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tx>
        PARSER = new com.google.protobuf.AbstractParser<Tx>() {
      public Tx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tx> getParserForType() {
      return PARSER;
    }

    public TxOuterClass.Tx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Txs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Txs_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010tx.proto\"\027\n\003Txs\022\020\n\003txs\030\001 \003(\0132\003.Tx\"\273\001\n\002" +
      "Tx\022\014\n\004from\030\001 \001(\014\022\n\n\002to\030\002 \001(\014\022\016\n\006amount\030\003" +
      " \001(\004\022\013\n\003fee\030\004 \001(\004\022\r\n\005nonce\030\005 \001(\r\022\021\n\tsign" +
      "ature\030\006 \001(\014\022\020\n\010recovery\030\007 \001(\r\022\033\n\023transit" +
      "ionSignature\030\010 \001(\014\022\032\n\022transitionRecovery" +
      "\030\t \001(\r\022\021\n\tnetworkid\030\n \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Txs_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Txs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Txs_descriptor,
        new java.lang.String[] { "Txs", });
    internal_static_Tx_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Tx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tx_descriptor,
        new java.lang.String[] { "From", "To", "Amount", "Fee", "Nonce", "Signature", "Recovery", "TransitionSignature", "TransitionRecovery", "Networkid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
